//This is used by the UITableViewCell in MapListViewController willDisplayCell
#define UITABLEVIEWCELL_DARK_BACKGROUND  [UIColor colorWithRed:151.0/255.0 green:152.0/255.0 blue:155.0/255.0 alpha:1.0]
#define UITABLEVIEWCELL_LIGHT_BACKGROUND [UIColor colorWithRed:172.0/255.0 green:173.0/255.0 blue:175.0/255.0 alpha:1.0]

#define TABLEVIEW_CELL_IMAGEVIEW_WIDTH			65.0f //This is fixed
#define TABLEVIEW_CELL_IMAGEVIEW_HEIGHT			65.0f

#define PADDING_TOP								 2.0f
#define PADDING_BOTTOM						 2.0f
#define PADDING_LEFT							 2.0f
#define PADDING_RIGHT							 2.0f

//The background size of the UIImageView in the PoiImageTableViewApplicationCell. This is bigger thus creating a white border effect
#define TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH		TABLEVIEW_CELL_IMAGEVIEW_WIDTH + PADDING_TOP + PADDING_BOTTOM
#define TABLEVIEW_CELL_THUMB_BACKGROUND_HEIGHT		TABLEVIEW_CELL_IMAGEVIEW_HEIGHT + PADDING_TOP + PADDING_BOTTOM

#define TABLEVIEW_CELL_HEIGHT						TABLEVIEW_CELL_THUMB_BACKGROUND_HEIGHT + PADDING_TOP + PADDING_BOTTOM

#define CELL_ACCESSORY_WIDTH					31.0f

//#define CONTENT_TEXT_ORIGIN_X					PADDING_LEFT + TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH + PADDING_RIGHT + PADDING_LEFT + CELL_ACCESSORY_WIDTH
#define CONTENT_TEXT_ORIGIN_X					PADDING_LEFT + TABLEVIEW_CELL_THUMB_BACKGROUND_WIDTH + PADDING_RIGHT + PADDING_LEFT

//#define CONTENT_TEXT_WIDTH					320.0f - (CONTENT_TEXT_ORIGIN_X - CELL_ACCESSORY_WIDTH)
#define CONTENT_TEXT_WIDTH					320.0f - CONTENT_TEXT_ORIGIN_X

#define STAR_WIDTH                65.0f
#define MENU_CELL_HEIGHT          44.0f
#define MENU_CELL_BACKGROUND      [UIColor colorWithRed:80.0/255.0 green:83.0/255.0 blue:84.0/255.0 alpha:1.0]